name: Lab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd project || exit 1
        if [ -f package.json ]; then
          npm install
        else
          echo "Error: package.json not found!"
          exit 1
        fi

    - name: Run tests
      run: |
        cd project || exit 1
        if [ -f package.json ]; then
          npm test
        else
          echo "Error: Cannot run tests without package.json!"
          exit 1
        fi
